apiVersion: v1
kind: Namespace
metadata:
  name: cassandra
  labels:
    name: cassandra
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cassandra
  namespace: cassandra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cassandra
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cassandra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cassandra
subjects:
- kind: ServiceAccount
  name: cassandra
  namespace: cassandra