apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cassandra-network-policy
  namespace: cassandra
spec:
  podSelector:
    matchLabels:
      app: cassandra
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: cassandra
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 7000
    - protocol: TCP
      port: 7001
    - protocol: TCP
      port: 9042
    - protocol: TCP
      port: 7199
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: cassandra
    ports:
    - protocol: TCP
      port: 7000
    - protocol: TCP
      port: 7001
    - protocol: TCP
      port: 9042
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: cassandra-secrets
  namespace: cassandra
type: Opaque
data:
  # Base64 encoded values - replace with your actual secrets
  cassandra-password: YWRtaW4xMjM=  # admin123
  keystore-password: Y2hhbmdlbWU=    # changeme
  truststore-password: Y2hhbmdlbWU=  # changeme
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cassandra-pdb
  namespace: cassandra
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app: cassandra